pkg/dashboard/static/index.html, pkg/dashboard/static/scripts.js
This commit adds the tool version to the UI in the top bar.
fix #33 
Visual Examples:
=> Add version information into UI

Makefile
Hi @undera, continuing contribution for refactoring makefile, I am adding some changes : 
- extra flag version and buildDate in build make command.
- adding unit test in make command
here is the result of executing make command
1. make test
`
$make test
start unit testing...
go: downloading k8s.io/apimachinery v0.25.0-alpha.2
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading github.com/hashicorp/go-version v1.6.0
go: downloading github.com/gin-gonic/gin v1.8.1
go: downloading github.com/hexops/gotextdiff v1.0.3
go: downloading helm.sh/helm/v3 v3.9.4
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/pkg/browser v0.0.0-20210911075715-681adbf594b8
go: downloading golang.org/x/sys v0.0.0-20220818161305-2296e01440c6
go: downloading …
=> refactoring makefile, also adding phony test

README.md, go.mod, main.go, pkg/dashboard/server.go
[Issue 75](https://github.com/komodorio/helm-dashboard/issues/75)
1. Adds `--bind` flag field in `options` in `main` package.
2. Function `StartServer` (and few other internal functions) made method(s) to a newly introduced type `Server`.
- Introduction of new flag `--bind` for binding-host-address to be read from CLI flag also (earlier: env and default only). The precedence order now is:
flag `--bind=<host>` > env `HD_BIND=<host>` > default value `localhost`
- `StartServer` and other internal functions are made methods to type `Server` in order to limit the number of arguments passed. This way, the code is cleaner.
Closes https://github.com/komodorio/helm-dashboard/issues/75
Given the current setup of function calls in most packages (observed specifically on `main`, `pkg/dashboard` and …
=> CLI Flag --bind

.github/workflows/release.yaml, charts/helm-dashboard/Chart.yaml, charts/helm-dashboard/README.md, charts/helm-dashboard/templates/serviceaccount.yaml, charts/helm-dashboard/values.yaml, plugin.yaml
1. Change chart icon
2. Allow all API groups
3. Allow write actions by default
=> Helm chart updates

charts/helm-dashboard/templates/deployment.yaml, charts/helm-dashboard/values.yaml
- Helps to set environment on debug mode
- Can fix #142
=> Added 'debug' flag in values

pkg/dashboard/objects/repos_test.go, pkg/dashboard/objects/testdata/repositories.yaml
Refs: #148 
- Test for [`Add`](https://github.com/komodorio/helm-dashboard/blob/998a5b84c58c8180e7e42f7532590d61f18bd68d/pkg/dashboard/objects/repos.go#L52)
- Modified the `repositories.yml` file
=> Test for adding repository

charts/helm-dashboard/templates/serviceaccount.yaml
A superfluous rule is added to the ClusterRole upon creation, when the dashboard.allowWriteActions value is set to true. This commit will ensure that only a single rule is created within the ClusterRole, regardless of whether the dashboard.allowWriteActions value is enabled or not.
The verbs within this rule will update accordingly.
Closes #186.
- Creates a single rule withing the ClusterRole, rather than two.
- Verb list for proposed single rule will be updated, according to value of `dashboard.allowWriteActions`
- When `dashboard.allowWriteActions` is `true`, write-oriented verbs will be include
- When `dashboard.allowWriteActions` is `false`, write-oriented verbs will be excluded
I have tested this locally and confirmed the ClusterRole updates accordingly.
=> 🎨 Remove Superfluous Rule from helm-dashboard ClusterRole

charts/helm-dashboard/README.md, charts/helm-dashboard/templates/deployment.yaml, charts/helm-dashboard/values.yaml
When changing a value in the values file and run upgrade command... both pods remaining running. The old one doesn't terminate and the new one can't start because of Multi-attach error. Same issue as here:
https://github.com/helm/charts/issues/12057
Added support for to change the strategy used to replace old Pods by new ones. 
Intended to fix the same issue as described here -> https://github.com/helm/charts/issues/12057
=> support for deployment strategy

charts/helm-dashboard/README.md, charts/helm-dashboard/templates/deployment.yaml, charts/helm-dashboard/values.yaml
This commit allows to pass arguments to the helm chart. This is useful if you want to specify arguments for the helm-dashboard binary whilst deploying via helm.
Closes #200 .
Arguments to the `helm-dashboard` binary can be supplied by utilising the `extraArgs` parameter within the supplied helm values.
=> 🔧 Allow binary arguments via helm chart

.github/labeler.yml, .github/workflows/release.yaml
- Update the release process.
- Today we are manually changing the plugin.yaml version and creating a tag. The release workflow runs once a tag is created.
- Using this process we will no longer need to manually create a tag and update plugin.yaml. 
- This worklow runs on every push to main and looks for the latest PR tags. If the tag is one of release-patch, release-minor or release-major - it bumps the version according to the label (patch/minor/major), updates and commits plugin.yaml and creates a tag. 
- If this PR is approved, I will need to create these tags so the flow would work.
- I did change the action which creates the github release, I wasn't sure the go-releaser action would work as expected in this new process.
- There is also an option of separating this flow to 2, one …
=> Update release workflow

go.mod, go.sum, pkg/dashboard/objects/data.go, pkg/dashboard/objects/data_test.go
Contributes towards #148 
- Add unit testing for the dashboard/objects/data.go NewDataLayer
- Add some argument checks in the NewDataLayer function to complement unit tests
Not a go unit testing expert, but went with the testing table approach.
Thanks for the review!
=> ✅ Add test for dashboard/objects/data.go NewDataLayer

pkg/dashboard/objects/releases_test.go
Contributes towards #148
* Added unit test for releases struct
Hi,
Have added a unit test for releases, if this format is good will add for the rest of the methods present in releases and maybe try for kubectl. Please take a look if there are any issues.
Thank You,
Arvind Sundara Rajan
=> Added unit tests for releases

charts/helm-dashboard/templates/pvc.yaml
Fix the missing use of storageClass in the helm chart.
I've already mistakingly opened this as https://github.com/komodorio/helm-charts/pull/145
=> fix: Make PVC use storageClass from values

pkg/dashboard/static/actions.js
#115
#178 
- Migrate existing API (for `helm test`) to use object model
=> Adding more information on UI for helm test API response

pkg/dashboard/handlers/helmHandlers.go, pkg/dashboard/static/list-view.js
=> Display UI indication if chart is upgradable

go.mod, main.go, pkg/dashboard/api_test.go, pkg/dashboard/objects/app.go, pkg/dashboard/objects/data.go, pkg/dashboard/objects/data_test.go, pkg/dashboard/objects/repos.go, pkg/dashboard/objects/repos_test.go, pkg/dashboard/objects/testdata/repositories-invalid-cache-file.yaml, pkg/dashboard/objects/testdata/repositories-malformed-manifest.yaml, pkg/dashboard/objects/testdata/testing-index.yaml, pkg/dashboard/server.go
[Issue][1] #94 
1. New CLI flag `--devel`.
2. Tests to cover `Charts()`  and `Containing()`.
CLI flag `--devel` to list/include development (prerelease versions like release candidate, alpha, beta, etc.) in the following endpoints:
- /api/helm/repositories/\<repo>
- /api/helm/repositories/versions?name=\<repo>
- /api/helm/repositories/latestver?name=\<repo>
Closes #94 
[1]: https://github.com/komodorio/helm-dashboard/issues/94
=> New CLI Flag `--devel` To Include Development/Prerelease Versions of Charts

pkg/dashboard/static/index.html, pkg/dashboard/static/list-view.js
- Open komodor.com/helm-dash link in tab
- Fixed installed chart 'Upgrade' indentation
=> Minor UI fixes

dashboard/package.json
Fix the storybook script from :
"storybook": "NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006",
to
"storybook": " **set** NODE_OPTIONS=--openssl-legacy-provider **&&** start-storybook -p 6006",
so now the storybook runs, before it did not.
=> Fix storybook script - did not worked before the change.

pkg/dashboard/static/analytics.js
Send analytics (of cluster mode and app version) to Segment data platform on app initialization
=> Send analytics to server

pkg/dashboard/handlers/helmHandlers.go, pkg/dashboard/objects/releases.go
Used dedicated Helm call to get individual release, instead of scanning full list always.
=> Optimize single release getting

pkg/dashboard/handlers/kubeHandlers.go
Added hdHealth status for PodDisruptionBudget and CRD. 
Below is the criterion for healthy status :
For CRD : if both the conditions (Established and NamesAccepted) are true.
For PodDisruptionBudget :  if condition DisruptionAllowed is true.
=> Handled resource kind PodDisruptionBudget and CRD for health status.

frontend/src/components/revision/RevisionsList.tsx, frontend/yarn.lock
Fixes #468.
I have fixed the issue of long numbers in the Revision Block.
**Before**
**After**
=> Improved revision block for long numbers

frontend/src/components/Badge.stories.tsx, frontend/src/components/Button.stories.tsx, frontend/src/components/ClustersList.stories.tsx, frontend/src/components/InstalledPackages/InstalledPackageCard.stories.tsx, frontend/src/components/InstalledPackages/InstalledPackagesHeader.stories.tsx, frontend/src/components/InstalledPackages/InstalledPackagesList.stories.tsx, frontend/src/components/SelectMenu.stories.tsx, frontend/src/components/ShutDownButton.stories.tsx, frontend/src/components/Tabs.stories.tsx, frontend/src/components/TabsBar.stories.tsx, frontend/src/components/TextInput.stories.tsx, frontend/src/components/Troubleshoot.stories.tsx, frontend/src/components/common/Button/Button.stories.tsx, frontend/src/components/common/DropDown.stories.tsx, frontend/src/components/common/Header/Header.stories.tsx, frontend/src/components/common/Page/Page.stories.tsx, frontend/src/components/common/StatusLabel.stories.tsx, frontend/src/components/modal/AddRepositoryModal.stories.tsx, frontend/src/components/modal/ErrorModal.stories.tsx, frontend/src/components/modal/Modal.stories.tsx, frontend/src/components/repository/ChartViewer.stories.tsx, frontend/src/components/repository/RepositoriesList.stories.tsx, frontend/src/components/repository/RepositoryViewer.stories.tsx
Basically, no component changes were made and the migration was done using Storybook's migration commands.
The parts that were updated manually are as follows
- Deletion of unnecessary modules loaded when the migration command was executed
- Type storage to resolve type errors
Details are left in the issue
https://github.com/komodorio/helm-dashboard/issues/486
- ~[ ] I have covered the changes with unit tests~
- Not supported as it is an unaffected area.
=> Migrated Storybook notation from CSF2 to CSF3

charts/helm-dashboard/README.md, charts/helm-dashboard/templates/_commons.tpl, charts/helm-dashboard/templates/_helpers.tpl, charts/helm-dashboard/templates/deployment.yaml, charts/helm-dashboard/templates/tests/test-connection.yaml, charts/helm-dashboard/values.yaml
1. fix `imagePullSecrets` bug in deployment.yaml
2. add `global` config
3. optimize image field with global registry config
this pr is for charts of helm-dashboard
1. fix `imagePullSecrets` bug in deployment.yaml
if use old deployment.yaml it will reported that e `expect map but get string`
2.  add `global` config
busybox image is hard code in the charts, so i propose to use `global.imageRegistry` to unify render of image. same with `imagePullSecrets`
=> update helm charts for helm-dashboard

pkg/dashboard/server.go
The number of historical release versions should not be unlimited. Refer to the official settings of Helm, set to 10 and can be configured through env `HELM_MAX_HISTORY`.
=> feat: Set history-max through env HELM_MAX_HISTORY (default 10)

pkg/dashboard/objects/releases.go, pkg/dashboard/server.go
Changes made in #500 did not work properly because the local variable `--history-max` of the cmd `helm upgrade` has a higher priority than the global one.
=> fix: history-max does not work when exec helm upgrade

pkg/dashboard/handlers/helmHandlers.go
It is now possible to disable the query through environment variable HD_NO_ARTIFACT_HUB_QUERY.
As suggested by @undera in #506
=> Added ability to disable query to ArtifactHub via env

pkg/dashboard/handlers/kubeHandlers.go
The pointer address returned from EnhanceStatus is now correctly set, following the same structure adopted in Resources function of /pkg/dashboard/handlers/helmHandlers.go
=> Fix resource status not enhanced for calls to /api/k8s/{kind}/get route

charts/helm-dashboard/templates/_helpers.tpl
This pull request optimizes the Helm chart code for assigning the image tag. The changes simplify the conditional assignment of the image tag using the `default` function.
**Changes:**
- Simplified the conditional assignment of the image tag using the `default` function in the Helm chart template.
This optimization improves the readability and maintainability of the Helm chart code.
=> Optimize Helm Chart Image Tag Assignment

charts/helm-dashboard/values.yaml
This pull request adds a `digest` field to the `image` block in the `values.yaml` file. The `digest` field allows specifying the exact image digest to pull, ensuring that the correct image version is used. 
Changes include:
- Added `digest` field to the `image` block in `values.yaml`
This change does not introduce any breaking changes and is backward compatible. The `digest` field is already utilized in the `_helpers.tpl` file, ensuring that the specified digest is used when constructing the image name.
=> Add digest field to image block in values.yaml

charts/helm-dashboard/templates/_helpers.tpl
This pull request updates the `helm-dashboard.serviceAccountName` template logic in the `_helpers.tpl` file to improve the handling of service account names. The changes include:
- Utilizing the `default` function to set the service account name based on the `serviceAccount.create` value.
- Ensuring that the service account name is generated using the `helm-dashboard.fullname` template when `serviceAccount.create` is true, otherwise defaulting to "default".
- Maintaining backward compatibility with existing configurations by preserving the use of `.Values.serviceAccount.name`.
These changes enhance the flexibility and robustness of the Helm chart's service account naming conventions.
=> Update helm-dashboard.serviceAccountName Template Logic in _helpers.tpl

frontend/src/App.tsx, frontend/src/pages/Installed.tsx
This PR addresses issue #557 by ensuring that the Helm Dashboard UI is accessible even if the cluster name contains a slash. The changes include:
- Added necessary encoding to the navigation path to prevent routing issues.
- Implemented decoding of cluster names to ensure proper display and functionality.
Closes #557.
=> Fix: Handle Cluster Names with Slashes in Helm Dashboard UI

charts/helm-dashboard/README.md, charts/helm-dashboard/templates/pvc.yaml, charts/helm-dashboard/values.yaml, frontend/cypress/fixtures/defaultReleases.json
This pull request introduces several changes to the persistent volume configuration in the Helm Dashboard chart, addressing concerns raised in GitHub issue #221. Key updates include:
1. **Removal of `hostPath` configuration:** The `hostPath` parameter has been removed from the configuration to discourage its use in production environments. This change aligns with best practices for production deployments, which typically avoid local host path volumes due to security and reliability concerns.
2. **Introduction of `finalizers`:** Added the `kubernetes.io/pvc-protection` finalizer to Persistent Volume Claims to prevent their deletion until associated resources are properly cleaned up. This ensures that data persistence is managed safely across the lifecycle of the resources.
3. **Dynamic …
=> Refactor Persistent Volume Configuration

charts/helm-dashboard/templates/service.yaml, charts/helm-dashboard/values.yaml
Changes Proposed
This PR introduces the ability to specify a loadBalancerIP for the Service when using the LoadBalancer type. This is particularly useful for offline deployments where a static IP is required for the service to function reliably.
The changes allow users to provide a loadBalancerIP field in the values.yml file, ensuring flexibility for setups in air-gapped or isolated environments. The Service template has been updated to conditionally include this field if it is specified.
Key Changes:
Updated the Service template to support loadBalancerIP.
Modified the values.yml file to include the loadBalancerIP field.
Documented the usage of loadBalancerIP in the values.yml example.
Check List
V  The title of my pull request is a short description of the changes
V  This PR relates to …
=> Add Support for Static LoadBalancer IP in Offline Deployments

go.mod
If the module is released at major version 2 or higher, the module path must end with a major version suffix like /v2. This may or may not be part of the subdirectory name
See https://go.dev/ref/mod#module-path
Fixing it will enable installing it locally with tools like [mise](https://mise.jdx.dev/) which currently default to the last v1: `mise use go:github.com/komodorio/helm-dashboard`
=> Fix modulepath

frontend/package.json, frontend/src/components/InstalledPackages/InstalledPackageCard.tsx
As discussed in #533 , loading status for all releases could be expensive. In this change, fetchings are made lazy, which means resources are not loaded until belonging component becomes visible.
=> Load resource status lazily 
