- pkg/dashboard/handlers/helmHandlers.go
Hi, I want to help update in helmHandlers.go file as I see the flow code can be simplified. 
Thank you
> removing else flow

- pkg/dashboard/utils/utils_test.go
Hi, I want to contribute on adding unit test for utils package.
```
/usr/local/go/bin/go test -json ./... -covermode=atomic -coverprofile /Users/macintosh/Library/Caches/JetBrains/GoLand2022.2/coverage/helm_dashboard$go_test_utils.out
=== RUN   TestGetQueryProps
=== RUN   TestGetQueryProps/Get_query_props_-_all_set_with_revRequired_true
=== RUN   TestGetQueryProps/Get_query_props_-_no_revision_with_revRequired_true
=== RUN   TestGetQueryProps/Get_query_props_-_no_namespace_with_revRequired_true
=== RUN   TestGetQueryProps/Get_query_props_-_no_name_with_revRequired_true
--- PASS: TestGetQueryProps (0.00s)
--- PASS: TestGetQueryProps/Get_query_props_-_all_set_with_revRequired_true (0.00s)
--- PASS: TestGetQueryProps/Get_query_props_-_no_revision_with_revRequired_true (0.00s)
--- PASS: …
```
> adding unit test for GetQueryProps (utils).

- README.md
- go.mod
- go.sum
- main.go
- pkg/dashboard/api.go
- pkg/dashboard/server.go
- pkg/dashboard/subproc/data.go
- pkg/dashboard/utils/utils.go
> Force namespace via cmdline parameter

- pkg/dashboard/static/actions.js
- pkg/dashboard/static/index.html
> Remove version check for charts without repo

- pkg/dashboard/static/actions.js
- pkg/dashboard/static/index.html
> Add current cluster info to Install and Upgrade popup

- main.go
> Pass the NS param from Helm correctly

- pkg/dashboard/api.go
- pkg/dashboard/handlers/kubeHandlers.go
- pkg/dashboard/static/actions.js
- pkg/dashboard/static/index.html
- pkg/dashboard/subproc/data.go
- pkg/dashboard/subproc/helmTypes.go
> Add namespace dropdown

- pkg/dashboard/static/scripts.js
> getCleanClusterName fixed

- pkg/dashboard/static/details-view.js
- pkg/dashboard/static/index.html
- pkg/dashboard/static/styles.css
- Sort kubernetes resources by bubbling up the interesting items - deployment, statefulset and deamonset.
- Remove shadow from installed chart header
> Sort resources by interesting items

- pkg/dashboard/static/list-view.js
> The chart icon does not display correctly

- pkg/dashboard/utils/utils.go
- pkg/dashboard/utils/utils_test.go
> fixbug: ChartAndVersion did not handle chart version correct in some case

- pkg/dashboard/static/scripts.js
> Bugfix: namespaces not updating when switching cluster

- pkg/dashboard/static/list-view.js
> Fixes JS part of #95

- pkg/dashboard/static/list-view.js
- pkg/dashboard/static/scripts.js
> Only display NS that has releases

- .github/workflows/release.yaml
> Fix CI - change output name

- pkg/dashboard/static/index.html
- pkg/dashboard/static/scripts.js
> Overlay with explanation modified

- pkg/dashboard/static/list-view.js
> Display correct message on installed charts page in case of an error

- plugin.yaml
Update plugin.yaml to recently released version for `helm plugin update` compatibility
> Release 0.3.0

- .github/ISSUE_TEMPLATE/bug.yaml
> feat: Add issue template

- pkg/dashboard/api_test.go
> Test for static route

- plugin.yaml
Update plugin.yaml to latest release version
> Release 0.3.1

- pkg/dashboard/api_test.go
> Tests: route configuration & context setter

- pkg/dashboard/api_test.go
> Test for `NewRouter` function

- pkg/dashboard/api_test.go
> Test for `configureScanners`

- .github/workflows/build.yml
> Changed version of action

- pkg/dashboard/api_test.go
> Test for `configureKubectls`

- .gitignore
- Added `.cov` extension to gitignore
> Ignore cover profile file

- pkg/dashboard/objects/repos_test.go
Refs: #148 
- Created `repos_test.go`
- Test: `Load()` of Repositories
> Test for repository loading

- scripts/install_plugin.sh
```
Downloading and installing helm-dashboard v0.3.1 ...
https://github.com/komodorio/helm-dashboard/releases/download/v0.3.1/helm-dashboard_0.3.1_Linux_x86_64.tar.gz
```
> Use github api to fetch latest release version

- pkg/dashboard/objects/repos_test.go
- pkg/dashboard/objects/testdata/repositories.yaml
Fixes issue of failing test of `Load()` in `Repositories`
- Fixes failing test of repo loading
> Fixes failing test

- .github/labeler.yml
> Add auto labeler for PR's

- pkg/dashboard/objects/repos_test.go
- pkg/dashboard/objects/testdata/repositories.yaml
Refs: #148 
- Written test for [`List`](https://github.com/komodorio/helm-dashboard/blob/9451a899d714ffecd7435318440a573421ce7c24/pkg/dashboard/objects/repos.go#L35)
- Added some mock up repositories to yaml file
- Did some code formatting
> Test for listing of repos

- pkg/dashboard/objects/repos_test.go
Refs: #148 
- Also added cleanup function for [`TestAdd`](https://github.com/komodorio/helm-dashboard/blob/a7a18eea422b1e49be8d306c0a0cc470e2c6d9c9/pkg/dashboard/objects/repos_test.go#L67-L94)
> Test for deleting the repository

- pkg/dashboard/objects/repos_test.go
> Test for getting repository

- .github/labeler.yml
- .github/workflows/pull-request-labeler.yaml
#152 
Reference: [create workflow](https://github.com/actions/labeler#create-workflow)
> Add github workflow for auto PR labeling

- README.md
The previous link has expired. Adding a never failing signup page: https://komodorkommunity.slack.com/
> Update Kommunity link

- .github/ISSUE_TEMPLATE/bug.yaml
- CONTRIBUTING.md
- pkg/dashboard/static/index.html
#183 
- Update Kommunity link across all files
> Update Kommunity link across all files

- pkg/dashboard/static/styles.css
> Break filters text when resizing window

- pkg/dashboard/api.go
- pkg/dashboard/handlers/helmHandlers.go
- pkg/dashboard/objects/releases.go
#115
#178 
- Migrate existing API (for `helm test`) to use object model
> Using object model to execute helm test

- .github/workflows/build.yml
- pkg/dashboard/api.go
- pkg/dashboard/api_test.go
- pkg/dashboard/handlers/helmHandlers.go
- pkg/dashboard/handlers/kubeHandlers.go
- pkg/dashboard/handlers/scannerHandlers.go
- pkg/dashboard/objects/releases.go
- pkg/dashboard/static/actions.js
- pkg/dashboard/static/api-docs.html
- pkg/dashboard/static/details-view.js
- pkg/dashboard/static/index.html
- pkg/dashboard/static/list-view.js
- pkg/dashboard/static/openapi.json
- pkg/dashboard/static/repo.js
- pkg/dashboard/static/revisions-view.js
- pkg/dashboard/static/scripts.js
- pkg/dashboard/utils/utils.go
- pkg/dashboard/utils/utils_test.go
> Rework API routes

- scripts/install_plugin.sh
Execute install script in debug mode only when HELM_DEBUG flag is set
> Execute install script in debug mode only when HELM_DEBUG flag is set

- main.go
- pkg/dashboard/handlers/helmHandlers.go
- pkg/dashboard/objects/artifacthub.go
- pkg/dashboard/static/actions.js
- pkg/dashboard/static/index.html
- pkg/dashboard/static/list-view.js
- pkg/dashboard/static/repo.js
> Query ArtifactHub for repo suggestion

- pkg/dashboard/handlers/helmHandlers.go
- pkg/dashboard/objects/repos.go
- pkg/dashboard/objects/repos_test.go
- pkg/dashboard/static/index.html
- pkg/dashboard/static/styles-base.css
- Add username and password support to Repo add form in UI
- Add support for
> Add username and password support to Repo add feature

- pkg/dashboard/api.go
- pkg/dashboard/handlers/helmHandlers.go
- pkg/dashboard/handlers/kubeHandlers.go
- pkg/dashboard/objects/kubectl.go
- pkg/dashboard/static/details-view.js
- pkg/dashboard/static/list-view.js
- pkg/dashboard/static/openapi.json
- pkg/dashboard/static/styles.css
> Display resource health aggregate icons on list of releases

- dashboard/src/components/modal/UninstallModal.stories.tsx
- dashboard/src/components/modal/UninstallModal.tsx
Implement Uninstall Modal with mocked data
> Implement Uninstall modal with mocked data

- dashboard/src/App.css
- dashboard/src/index.css
- Fixed header position
- Full-length body (removing scroll)
> Fixed header position

- dashboard/package.json
- dashboard/src/components/common/DropDown.stories.tsx
- dashboard/src/components/common/DropDown.tsx
- dashboard/src/layout/Header.tsx
> Finish "Help menu"

- dashboard/src/components/ClustersList.tsx
> Install page - Clusters list

- dashboard/src/layout/Header.tsx
Finish the Infrastructure helm experience link
> Finish the Infrastructure helm experience link

- dashboard/src/components/modal/AddRepositoryModal.stories.tsx
- dashboard/src/components/modal/AddRepositoryModal.tsx
- dashboard/src/components/modal/InstallModal.tsx
- dashboard/src/components/repository/RepositoriesList.tsx
> Implement Add repository modal base UI

- dashboard/src/App.tsx
- dashboard/src/components/ClustersList.tsx
- dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
- dashboard/src/components/InstalledPackages/InstalledPackagesHeader.tsx
- dashboard/src/components/InstalledPackages/InstalledPackagesList.tsx
- dashboard/src/data/types.ts
- dashboard/src/pages/Installed.tsx
- dashboard/src/pages/Revision.tsx
- dashboard/src/timeUtils.ts
* use real data in the installed page
* navigate from the installed page to revision when clicking the installed package
* add an 'upgrade' label on the install page:
> Open revisions

- dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
- dashboard/src/components/common/StatusLabel.tsx
- dashboard/src/components/revision/RevisionDetails.tsx
- dashboard/src/components/revision/RevisionsList.tsx
- dashboard/src/data/types.ts
- dashboard/src/pages/Revision.tsx
- dashboard/src/timeUtils.ts
* Create ReleaseRevision type and use it
* Make the Revisions list selectable
* Add StatusLabel component
> Create ReleaseRevision type and use it

- dashboard/src/components/revision/RevisionResource.tsx
- dashboard/src/components/revision/RevisionTabs.tsx
> Revisions Page - Tabs - Resources - UI

- pkg/dashboard/static/actions.js
- Sort release version in Install modal by semver
> bug: fix sorting of release versions

- .github/labeler.yml
- Auto label all PD related to helm-dashboard-v2
> feat: auto labeler for helm-dashboard-v2

- .github/workflows/build.yml
- .github/workflows/release.yaml
- Dockerfile
> Build and release ARM docker images

- .github/workflows/build.yml
- .github/workflows/release.yaml
> Change commit message of chart release

- dashboard/src/layout/Header.tsx
Just a minor fix for the upgrade button to be open in a new tab
> Fix-377/upgrade-button

- dashboard/.eslintrc.cjs
- dashboard/index.html
- dashboard/public/scripts/analytics.js
- dashboard/tsconfig.json
This is integration of the analytics script in the old project
> Task-375-Analytics script integration

- dashboard/src/components/InstalledPackages/InstalledPackagesHeader.tsx
> Empty state2

- dashboard/src/components/modal/AddRepositoryModal.tsx
- dashboard/src/index.css
- dashboard/tailwind.config.cjs
Add 2 fields for username and password to the `Add repository` form.
Align the UI.
Add new font on tailwind.
- [x ] The title of my pull request is a short description of the changes
> Fix | Add more fields to add repository form

- dashboard/src/API/apiService.ts
- dashboard/src/components/revision/RevisionsList.tsx
- dashboard/src/pages/Revision.tsx
- dashboard/yarn.lock
- pkg/dashboard/api.go
fixed sort of releases.
Added the option to select a release
Added the updated version label of releases.
> fix revision releases

- dashboard/src/API/releases.ts
- dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
- dashboard/src/components/revision/RevisionDetails.tsx
- dashboard/yarn.lock
> Reconfigure version diff

- dashboard/src/components/Tabs.tsx
- dashboard/src/components/revision/RevisionDiff.tsx
- dashboard/src/components/revision/RevisionsList.tsx
- dashboard/src/hooks/useCustomSearchParams.ts
> add user defined

- dashboard/src/App.tsx
- dashboard/src/components/repository/RepositoryViewer.tsx
- dashboard/src/components/revision/RevisionDetails.tsx
- dashboard/src/context/AppContext.tsx
- dashboard/src/pages/Installed.tsx
> chart install fix

- dashboard/src/components/modal/InstallChartModal/InstallChartModal.tsx
- dashboard/src/layout/Header.tsx
> fixed redirects and nav links selected ui

- dashboard/src/pages/Revision.tsx
> loading ui while fetching history in revision page

- dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
- dashboard/src/timeUtils.ts
> Fix N/A age on installed package card

- scripts/install_plugin.sh
Refactored the installation script to improve functionality, efficiency, and maintainability.
I have made the following changes to the script:
- Replaced inconsistent variable usage with consistent usage of the `name` variable.
- Introduced functions to encapsulate repetitive code blocks.
- Handled errors gracefully and provided informative error messages.
- Validated the availability of required dependencies.
- Used consistent indentation and formatting throughout the script.
- Separated concerns into separate functions for version detection, downloading, and installation.
- [ x] The title of my pull request is a short description of the changes
- [ x] I have documented the changes made (if applicable)
- [ x] I have covered the changes with unit tests
> Refactoring install plugin script

- dashboard/index.html
> remove diff2html css html dep

- dashboard/src/components/common/StatusLabel.stories.tsx
- dashboard/yarn.lock
> Adding storybook for StatusLabel component

- dashboard/src/hooks/useCustomSearchParams.ts
> missing dep in hooks

- dashboard/src/components/modal/InstallChartModal/GeneralDetails.tsx
- dashboard/src/components/modal/InstallChartModal/InstallReleaseChartModal.tsx
- dashboard/src/components/modal/InstallChartModal/UserDefinedValues.tsx
- dashboard/src/hooks/useDebounce.tsx
> Namespace debounce

- dashboard/src/index.css
Added base layer for the body styling inside `index.css`
> Adding layer to base style

- dashboard/src/components/modal/InstallChartModal/InstallReleaseChartModal.tsx
- dashboard/src/components/modal/InstallChartModal/InstallRepoChartModal.tsx
- dashboard/src/data/types.ts
The exact same type was inside `installReleaseChartModal` and `installRepoChartModal` - extracted into the types file
> Extract duplicate type to types file

- dashboard/src/API/k8s.ts
- dashboard/src/API/other.ts
- dashboard/src/API/releases.ts
- dashboard/src/API/repositories.ts
- dashboard/src/API/scanners.ts
- dashboard/src/components/modal/AddRepositoryModal.tsx
- dashboard/src/components/repository/RepositoryViewer.tsx
> Refactor callApi into direct usage of apiService

- dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
- dashboard/yarn.lock
On smaller screens (not mobile tho) we now have room between the HealthStatus grid and the chart version:
> Give some room for multiple HealthStatus

- dashboard/src/components/modal/InstallChartModal/DefinedValues.tsx
- dashboard/src/components/modal/InstallChartModal/InstallReleaseChartModal.tsx
- dashboard/src/components/modal/InstallChartModal/InstallRepoChartModal.tsx
- dashboard/src/components/modal/InstallChartModal/UserDefinedValues.tsx
> Extract defined values from the Modals

- charts/helm-dashboard/README.md
- pkg/dashboard/api_test.go
- pkg/dashboard/static/openapi.json
- pkg/dashboard/utils/utils.go
> fix some typos

- frontend/.storybook/main.ts
- frontend/src/components/Button.stories.tsx
- frontend/src/components/ClustersList.stories.tsx
- frontend/src/components/SelectMenu.stories.tsx
- frontend/src/components/common/DropDown.stories.tsx
- frontend/src/components/modal/ErrorModal.stories.tsx
- frontend/src/components/modal/Modal.stories.tsx
- frontend/src/components/modal/Modal.tsx
Closes: #488 
Refactoring related to Storybook was done.
Details are left in the issue
> Removal of ignore notation in storybook eslint and transition to actions function

- README.md
I added some missing articles and corrected “NodeJS” to the official spelling “Node.js” ☺️
> corrected grammar and spelling in README.md
